### PR TITLE
update notebook version

### PR DESCRIPTION
**Pull request by kain88-de**
updates to the current release

### CODE REVIEW

**Comment by minrk** [comment]
Thanks! The CI failed because it needed a re-render (#14). We're just about to release 4.3.1 (hopefully today) with some important fixes, so maybe we can wait for that?

**Comment by kain88-de** [comment]
Sure I can wait a few more days, then the recipe can also be rerendered.

**Comment by minrk** [comment]
Just released 4.3.1, if you want to rebase and update to that version.

**Comment by kain88-de** [comment]
rebased and updated to 4.3.1

**Comment by jakirkham** [comment]
Please also enable CircleCI on your fork.

**Comment by kain88-de** [comment]
@jakirkham How was the CircleCI build disabled here? The file for the build exists. If you are complaining that the CircleCi build doesn't happen on this PR and it has to do with the settings of *this* repository.

**Comment by jakirkham** [comment]
Please see issue ( https://github.com/conda-forge/status/issues/30 ) for details.

**Comment by kain88-de** [comment]
I've enabled circleCI

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
