### PR TITLE
Use conda-smithy to regenerate the feedstock

### PR DESCRIPTION
**Pull request by ericdill**
@jasongrout this is the process for regenerating with conda smithy
```
conda install conda-smithy -c conda-forge
conda smithy regenerate /path/to/notebook/feedstock
```

### CODE REVIEW

**Comment by ericdill** [comment]
@minrk happy to help with maintenance if you'd like.  I can add myself as a maintainer, but want your go-ahead first :grinning:

**Comment by minrk** [comment]
@ericdill thanks! Feel free to add yourself. I think we should bump the build number, too.

**Comment by ericdill** [comment]
@minrk sorry i never looped back to this. got sidetracked by the pydata carolinas conference wed-fri of last week.  I think we do not need to bump the build number since you released 4.2.3, right?

**Comment by minrk** [comment]
Yup, I think it's fine.

**Pull request merged**
