### PR TITLE
Update dependencies based on latest Notebook release

### PR DESCRIPTION
**Pull request by lresende**
Updating these dependencies should avoid kernel issues on windows
environment, see https://github.com/jupyter/notebook/issues/5124

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by takluyver** [comment]
Looks like we've got dependency conflicts in some cases, while the Travis PowerPC builds are failing in a different way.

**Comment by mariusvniekerk** [comment]
the travis builds need a rerender

**Comment by lresende** [comment]
@mariusvniekerk Could this be failing because Jupyter Client 5.3.4 might not have been pushed properly to conda-forge repos? See https://github.com/conda-forge/jupyter_client-feedstock/commits/master

**Comment by bollwyvl** [comment]
>  because Jupyter Client 5.3.4 might not have been pushed properly

The osx one is there, so not sure what that's about, but the ppc38 is indeed missing...

**Comment by bollwyvl** [comment]
All of this is up for `6.0.2`:
Closed by #63, everything up on https://anaconda.org/conda-forge/notebook/files?version=6.0.2
```
linux-64/notebook-6.0.2-py36_0.tar.bz2
linux-64/notebook-6.0.2-py37_0.tar.bz2
linux-64/notebook-6.0.2-py38_0.tar.bz2
linux-aarch64/notebook-6.0.2-py36_0.tar.bz2
linux-aarch64/notebook-6.0.2-py37_0.tar.bz2
linux-aarch64/notebook-6.0.2-py38_0.tar.bz2 
linux-ppc64le/notebook-6.0.2-py36_0.tar.bz2
linux-ppc64le/notebook-6.0.2-py37_0.tar.bz2
linux-ppc64le/notebook-6.0.2-py38_0.tar.bz2
osx-64/notebook-6.0.2-py36_0.tar.bz2
osx-64/notebook-6.0.2-py37_0.tar.bz2
osx-64/notebook-6.0.2-py38_0.tar.bz2
win-64/notebook-6.0.2-py36_0.tar.bz2
win-64/notebook-6.0.2-py37_0.tar.bz2
win-64/notebook-6.0.2-py38_0.tar.bz2
```

@lresende If we need it for `6.0.1`, we can do a backport of the pins, otherwise would advocate for closing...

**Pull request closed without merging**
