### PR TITLE
Update to 5.4.0

### PR DESCRIPTION
**Pull request by takluyver**
Just released to fix a regression with creating notebooks in subdirectories.

### CODE REVIEW

**Comment by takluyver** [comment]
Tests have passed if someone wants to press the button. I don't currently have buttoning access to this feedstock.

**Comment by jakirkham** [comment]
Feel free to add yourself. Can add `[ci skip]` in the subject line of the commit to skip CI.

**Comment by takluyver** [comment]
Myeh, I typed it with a hyphen instead of a space.

**Comment by minrk** [comment]
Merged both this and #27 so that we still have a build of 5.3.1 with fixed dependencies.

**Pull request merged**
