### PR TITLE
Upgrade to notebook 5.2.0

### PR DESCRIPTION
**Pull request by gnestor**

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @gnestor.

**Comment by jakirkham** [comment]
Also you should get a GitHub email invite to join conda-forge. Please let me know if you didn't get it. Could be old or sorted into spam by mistake.

**Comment by gnestor** [comment]
Thanks @jakirkham! I didn't get the email, can you re-send?

**Comment by jakirkham** [comment]
Not sure. I can try.

Also could you please try navigating to https://github.com/conda-forge and seeing if an invite shows up at the top of the page.

**Comment by gnestor** [comment]
That worked 👍👍

**Pull request merged**
