### PR TITLE
Release 5.1 & re-render with conda-smithy

### PR DESCRIPTION
**Pull request by takluyver**
Continuation of #18.

### CODE REVIEW

**Comment by minrk** [comment]
I'll let Travis finish the real build.

**Comment by jakirkham** [comment]
Yeah Travis CI has been going incredibly slowly the past few days. Wouldn't be surprised if there isn't something else wrong with their infrastructure again. 😞

**Comment by SylvainCorlay** [comment]
Do we need to wait for travis builds for pure python packages?

**Comment by takluyver** [comment]
[It looks like](https://www.traviscistatus.com/) the Mac builders had problems for a few days last week, and it might still be backlogged. The queue has been >1000 for all of the last 24 hours.

Is conda-forge doing anything with `noarch: python` to streamline builds? Someone was suggesting that in one of our other feedstocks.

**Comment by jakirkham** [comment]
Travis CI is easily a day or more behind right now.

We have been trying to move things to `noarch: python`. These build on CircleCI only.

However like any big campaign having more people spreading the word, documenting things, answering questions, etc. will be necessary for it to acquire the necessary bandwidth. By which I mean, bandwidth enough to both switch things and curb the swell in new Travis CI builds.

**Comment by Carreau** [comment]
> However like any big campaign having more people spreading the word, documenting things, answering questions, etc

Did the conda-forge twitter account tweet anything about that, happy to retweet with Jupyter/IPython accounts.

**Comment by jakirkham** [comment]
I don't know if we have a conda-forge twitter account. If we do, @pelson would know. A tweet would be great.

We did add it on Gitter. Also on our [RTD]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ) page. Should show up on the webpage as well.

**Comment by ocefpaf** [comment]
> I'll suggest making it a tweet-deck group so that user can tweet/retweet from it without having to log in and out.

Awesome idea. That is what we wanted but I did not know about tweet-deck.

Ping @ericdill

**Comment by jakirkham** [comment]
> One thing which is unclear to me in the RTD page is if no-arch are still ok with conditional platform dependencies.

FWIU they are not. Was going to send a follow-up PR to make that clear. @msarahan @jjhelmus care to add?

**Comment by msarahan** [comment]
No support for conditional platform deps. PRs to add such functionality are welcome. They'll probably be changes to both conda and conda build.

**Comment by Carreau** [comment]
> No support for conditional platform deps.

:-( 

Can't switch IPython then :-( I'll wait, and add sending a PR to fix this somewhere on my todo list.

**Comment by jakirkham** [comment]
> No support for conditional platform deps. PRs to add such functionality are welcome.

Thanks for the confirm, @msarahan. Glad to hear it could be an option.

> Should we move this discussion somewhere else also ? I'm going to release IPython probably later today, I'm happy to make a paragraph venting the benefits of noarch on the blog post announce.

Sure. Let's open an issue on the webpage repo. Would you like to start us off, @Carreau?

**Comment by Carreau** [comment]
> One thing which is unclear to me in the RTD page is if no-arch are still ok with conditional platform dependencies.

Actually it is on the RTD page, I just miss read, I scanned for "conditional dependency" and "fixed requirements" did not match with my brain. 

Happy to still open an issue for better phrasing.

**Comment by jakirkham** [comment]
Go for it! If you think it is unclear, probably others do too.

**Comment by Carreau** [comment]
See https://github.com/conda-forge/conda-forge.github.io/issues/443

**Pull request merged**
