### PR TITLE
[wip] 6.0.2 update metadata

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a smash-up of #60 and #57, plus a once-over on the metadata, and adding myself. Wanted to give it a run otherwise as-is, but there is the potential for:
- adding the tests, as not doing so has let some things through
  - much will continue to fail on windows/38 until https://github.com/ipython/ipykernel/pull/456 is released
- trying `noarch: python` again, as the reservations in #33 seem no longer relevant, 
  - would slim things down (but only after determining if is otherwise viable)

### CODE REVIEW

**Comment by bollwyvl** [comment]
Initial drone/travis fails are likely CDN... will try again in a bit...

**Comment by bollwyvl** [comment]
I'm getting a valid solves for `aarch` and `py38`
```
CONDA_SUBDIR=linux-aarch64 conda create -n foo --json --dry-run -c conda-forge -c c4aarch64 python=3.8 ipykernel ipython_genutils jinja2 jupyter_core >=4.6.0 jupyter_client >=5.3.4 nbconvert nbformat pyzmq >=17 send2trash terminado >=0.8.1 tornado >=5.0,<7 traitlets >=4.2.1 prometheus_client
```

and `ppc`
```
CONDA_SUBDIR=linux-ppc64le conda create -n foo --json --dry-run -c conda-forge -c defaults python=3.8 ipykernel ipython_genutils jinja2 jupyter_core >=4.6.0 jupyter_client >=5.3.4 nbconvert nbformat pyzmq >=17 send2trash terminado >=0.8.1 tornado >=5.0,<7 traitlets >=4.2.1 prometheus_client
```
...so trying again

**Comment by bollwyvl** [comment]
ah, drone is not starting. Will see how travis goes, but might close/reopen this.

**Comment by lresende** [comment]
Thanks @bollwyvl

**Pull request closed without merging**
