### PR TITLE
notebook 6.0.2, update metadata, pip check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- re-submission of #62 because of https://github.com/conda-forge/conda-forge.github.io/issues/954 (probably)

### CODE REVIEW

**Comment by bollwyvl** [comment]
Great, drone started:
https://cloud.drone.io/conda-forge/notebook-feedstock/9

**Comment by bollwyvl** [comment]
Whew!

**Comment by jasongrout** [comment]
ping @SylvainCorlay @lresende @takluyver again as some possibilities for a review/merge.

**Comment by bollwyvl** [comment]
Hooray!

**Pull request merged**
